/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication11.view;

import javaapplication11.service.MouseListenerJLabel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import javaapplication11.model.Employees;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Nguyen Duy Hung
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public static Employees currentEmployee;
    public HomePage() {
        initComponents();
        this.setLocationRelativeTo(null);
        if(currentEmployee != null) lblEmployeeName.setText(currentEmployee.getName());
        JPanel pnViews = new JPanelHomePage().getPanel();
        
        pnMainPage.removeAll();
        pnMainPage.add(pnViews);
        pnMainPage.validate();
        pnMainPage.repaint();
        lblEmployees.addMouseListener(new MouseListenerJLabel(lblEmployees, pnEmployees){
            @Override
            public void mouseClicked(MouseEvent e) {
                lblHomePage.setForeground(Color.BLACK);
                lblLogout.setForeground(Color.BLACK);
                lblOrders.setForeground(Color.BLACK);
                lblProducts.setForeground(Color.BLACK);
                lblTotal.setForeground(Color.BLACK);
                pnEmployees.setBackground(Color.WHITE);
                lblEmployees.setForeground(Color.RED);
            }
            
        });
        lblHomePage.addMouseListener(new MouseListenerJLabel(lblHomePage, pnHomePage){
            @Override
            public void mouseClicked(MouseEvent e) {
                lblEmployees.setForeground(Color.BLACK);
                lblLogout.setForeground(Color.BLACK);
                lblOrders.setForeground(Color.BLACK);
                lblProducts.setForeground(Color.BLACK);
                lblTotal.setForeground(Color.BLACK);
                pnHomePage.setBackground(Color.WHITE);
                lblHomePage.setForeground(Color.RED);
            }

            
        });
        lblLogout.addMouseListener(new MouseListenerJLabel(lblLogout, pnLogOut){
            @Override
            public void mouseClicked(MouseEvent e) {
                lblEmployees.setForeground(Color.BLACK);
                lblHomePage.setForeground(Color.BLACK);
                lblOrders.setForeground(Color.BLACK);
                lblProducts.setForeground(Color.BLACK);
                lblTotal.setForeground(Color.BLACK);
                pnLogOut.setBackground(Color.WHITE);
                lblLogout.setForeground(Color.RED);
            }
        });
        lblOrders.addMouseListener(new MouseListenerJLabel(lblOrders, pnOrders){
            @Override
            public void mouseClicked(MouseEvent e) {
                lblEmployees.setForeground(Color.BLACK);
                lblHomePage.setForeground(Color.BLACK);
                lblLogout.setForeground(Color.BLACK);
                lblProducts.setForeground(Color.BLACK);
                lblTotal.setForeground(Color.BLACK);
                pnOrders.setBackground(Color.WHITE);
                lblOrders.setForeground(Color.RED);
            }
        });
        lblProducts.addMouseListener(new MouseListenerJLabel(lblProducts, pnProducts){
            @Override
            public void mouseClicked(MouseEvent e) {
                lblEmployees.setForeground(Color.BLACK);
                lblHomePage.setForeground(Color.BLACK);
                lblLogout.setForeground(Color.BLACK);
                lblOrders.setForeground(Color.BLACK);
                lblTotal.setForeground(Color.BLACK);
                pnProducts.setBackground(Color.WHITE);
                lblProducts.setForeground(Color.RED);
            }
        });
        lblTotal.addMouseListener(new MouseListenerJLabel(lblTotal, pnTotals){
            @Override
            public void mouseClicked(MouseEvent e) {
                lblEmployees.setForeground(Color.BLACK);
                lblHomePage.setForeground(Color.BLACK);
                lblLogout.setForeground(Color.BLACK);
                lblOrders.setForeground(Color.BLACK);
                lblProducts.setForeground(Color.BLACK);
                pnTotals.setBackground(Color.WHITE);
                lblTotal.setForeground(Color.RED);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        pnHomePage = new javax.swing.JPanel();
        lblHomePage = new javax.swing.JLabel();
        pnProducts = new javax.swing.JPanel();
        lblProducts = new javax.swing.JLabel();
        pnOrders = new javax.swing.JPanel();
        lblOrders = new javax.swing.JLabel();
        pnEmployees = new javax.swing.JPanel();
        lblEmployees = new javax.swing.JLabel();
        pnTotals = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        pnLogOut = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        pnMainPage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setText("Quan Ly Nha Hang");

        jLabel3.setText("Nhan Vien:");

        lblEmployeeName.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        pnHomePage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHomePage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHomePage.setText("Home Page");
        lblHomePage.setName("HomePage"); // NOI18N
        lblHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHomePageMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnHomePageLayout = new javax.swing.GroupLayout(pnHomePage);
        pnHomePage.setLayout(pnHomePageLayout);
        pnHomePageLayout.setHorizontalGroup(
            pnHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnHomePageLayout.setVerticalGroup(
            pnHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnProducts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblProducts.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblProducts.setText("Products");
        lblProducts.setName("Products"); // NOI18N
        lblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblProductsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnProductsLayout = new javax.swing.GroupLayout(pnProducts);
        pnProducts.setLayout(pnProductsLayout);
        pnProductsLayout.setHorizontalGroup(
            pnProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnProductsLayout.setVerticalGroup(
            pnProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnOrders.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblOrders.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblOrders.setText("Orders");
        lblOrders.setName("Orders"); // NOI18N
        lblOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrdersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnOrdersLayout = new javax.swing.GroupLayout(pnOrders);
        pnOrders.setLayout(pnOrdersLayout);
        pnOrdersLayout.setHorizontalGroup(
            pnOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnOrdersLayout.setVerticalGroup(
            pnOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnEmployees.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblEmployees.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEmployees.setText("Employees");
        lblEmployees.setToolTipText("Employees");
        lblEmployees.setName("Employees"); // NOI18N
        lblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEmployeesMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnEmployeesLayout = new javax.swing.GroupLayout(pnEmployees);
        pnEmployees.setLayout(pnEmployeesLayout);
        pnEmployeesLayout.setHorizontalGroup(
            pnEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmployeesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnEmployeesLayout.setVerticalGroup(
            pnEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmployeesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnTotals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotal.setText("Revenue");
        lblTotal.setName("Total"); // NOI18N
        lblTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTotalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnTotalsLayout = new javax.swing.GroupLayout(pnTotals);
        pnTotals.setLayout(pnTotalsLayout);
        pnTotalsLayout.setHorizontalGroup(
            pnTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTotalsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTotalsLayout.setVerticalGroup(
            pnTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTotalsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnLogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblLogout.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLogout.setText("Log Out");
        lblLogout.setName("LogOut"); // NOI18N
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLogoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnLogOutLayout = new javax.swing.GroupLayout(pnLogOut);
        pnLogOut.setLayout(pnLogOutLayout);
        pnLogOutLayout.setHorizontalGroup(
            pnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnLogOutLayout.setVerticalGroup(
            pnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnTotals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTotals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnHomePage.setBackground(Color.LIGHT_GRAY);
        pnProducts.setBackground(Color.LIGHT_GRAY);
        pnOrders.setBackground(Color.LIGHT_GRAY);
        pnEmployees.setBackground(Color.LIGHT_GRAY);
        pnTotals.setBackground(Color.LIGHT_GRAY);
        pnLogOut.setBackground(Color.LIGHT_GRAY);

        pnMainPage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnMainPage.setPreferredSize(new java.awt.Dimension(670, 4));

        javax.swing.GroupLayout pnMainPageLayout = new javax.swing.GroupLayout(pnMainPage);
        pnMainPage.setLayout(pnMainPageLayout);
        pnMainPageLayout.setHorizontalGroup(
            pnMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        pnMainPageLayout.setVerticalGroup(
            pnMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMainPage, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnMainPage, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomePageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomePageMousePressed
        // TODO add your handling code here:
         if(this.checkRoll() != -1){
            JPanel pnViews = new JPanelHomePage().getPanel();
            pnMainPage.removeAll();
            pnMainPage.add(pnViews);
            pnMainPage.validate();
            pnMainPage.repaint();
         }
    }//GEN-LAST:event_lblHomePageMousePressed

    private void lblProductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductsMousePressed
        // TODO add your handling code here:
             JPanel pnViews = new JPanelProducts().getPanel();
            pnMainPage.removeAll();
            pnMainPage.add(pnViews);
            pnMainPage.validate();
            pnMainPage.repaint();

    }//GEN-LAST:event_lblProductsMousePressed

    private void lblEmployeesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeesMousePressed
        // TODO add your handling code here:
         if(this.checkRoll() == 2){
             JPanel pnViews = new JPanelEmployees().getPanel();
            pnMainPage.removeAll();
            pnMainPage.setPreferredSize(new Dimension(pnViews.getWidth(), pnViews.getHeight()));
            pnMainPage.add(pnViews);
            pnMainPage.validate();
            pnMainPage.repaint();
         }else{
            JOptionPane.showMessageDialog(this, "Ban khong du quyen");
        }
    }//GEN-LAST:event_lblEmployeesMousePressed

    private void lblOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrdersMouseClicked
        // TODO add your handling code here:
        if(this.checkRoll() == 2){
            JPanel pnViews = new JPanelOrder().getPanel();
         pnMainPage.removeAll();
   
         pnMainPage.setPreferredSize(new Dimension(pnViews.getWidth(), pnViews.getHeight()));
         pnMainPage.add(pnViews);
         pnMainPage.validate();
         pnMainPage.repaint();
        }else{
            JOptionPane.showMessageDialog(this, "Ban khong du quyen");
        }
    }//GEN-LAST:event_lblOrdersMouseClicked

    private void lblTotalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotalMousePressed
        // TODO add your handling code here:
        if(this.checkRoll() == 2){
            JPanel pnViews = new JPanelTotal().getPanel();
         pnMainPage.removeAll();
   
         pnMainPage.setPreferredSize(new Dimension(pnViews.getWidth(), pnViews.getHeight()));
         pnMainPage.add(pnViews);
         pnMainPage.validate();
         pnMainPage.repaint();
        }else{
            JOptionPane.showMessageDialog(this, "Ban khong du quyen");
        }
    }//GEN-LAST:event_lblTotalMousePressed

    private void lblLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMousePressed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Ban chac chan muon dang xuat?");
        if(confirm == JOptionPane.YES_OPTION){
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblLogoutMousePressed

    /**
     * @param args the command line arguments
     */
    private int checkRoll(){
        int role = -1;
        if(currentEmployee != null){
            role=currentEmployee.getRole();
        }
        return role;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblEmployees;
    private javax.swing.JLabel lblHomePage;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblOrders;
    private javax.swing.JLabel lblProducts;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnEmployees;
    private javax.swing.JPanel pnHomePage;
    private javax.swing.JPanel pnLogOut;
    private javax.swing.JPanel pnMainPage;
    private javax.swing.JPanel pnOrders;
    private javax.swing.JPanel pnProducts;
    private javax.swing.JPanel pnTotals;
    // End of variables declaration//GEN-END:variables
}
